- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
   - name: Install Nginx
     ansible.builtin.dnf:
       name: nginx
       state: latest

   - name: Copy Expense Nginx Configuration
     ansible.builtin.template:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf


   - name: Clean The Old Content
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent

   - name: Create App Directory
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: directory

   - name: Download and Extract App Content - From Artifactory
     ansible.builtin.unarchive:
       src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
       dest: /usr/share/nginx/html
       remote_src: yes



   - name: Start Nginx
     ansible.builtin.systemd_service:
       name: nginx
       state: restarted
       enabled: yes


