- name: Disable default NodeJS Version Module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS Module for V20
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Adding Application User
  ansible.builtin.user:
    name: expense

- name: Clean The Old Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract App Content - From Artifactory
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes

- name: Download NodeJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Copy Backend Service File
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      PyMySQL
      cryptography
    executable: 3.9



- name: Start Backend Service
  ansible.builtin.systemd_service:
    name: backend
    state: started
    enabled: yes
    daemon-reload: yes

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.rajdevops.online
