- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

#- name: Load Schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/schema/backend.sql
#    login_user: root
#    login_password: ExpenseApp@1


- name: Check the DB connection with our password
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.rajdevops.online
    filter: version
  register: mysql_connection_output
  ignore_errors: yes



- name: Setup MySQL password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}
  when: mysql_connection_output.failed is true